import { Audiowide } from "next/font/google";
import "@/scss/main.scss";
import AuthProvider from "@/providers/AuthContext";

const inter = Audiowide({ weight: "400", subsets: ["latin-ext"] });

export const metadata = {
  title: "KenzieContacts",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="pt">
      <body className={inter.className}>
        <AuthProvider>{children}</AuthProvider>
      </body>
    </html>
  );
}
